# Generated by Django 6.0.6 on 2026-06-16 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance_usdt', models.FloatField(default=1000)),
                ('btc', models.FloatField(default=0)),
            ],
        ),
    ]
