# Generated by Django 6.0.6 on 2026-06-16 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wallet',
            old_name='btc',
            new_name='doge',
        ),
    ]
